from __future__ import annotations

from pathlib import Path

from artifacts.artifact_manager import ensure_export_dir


from core.app_identity import APP_NAME


def create_python_script(task: str, output_name: str = "generated_script.py") -> Path:
    path = ensure_export_dir() / output_name
    content = f'''"""
Generated by {APP_NAME}.
Task: {task}
"""


def main():
    # TODO: 按实际业务完善脚本逻辑。
    print("{APP_NAME} generated script")


if __name__ == "__main__":
    main()
'''
    path.write_text(content, encoding="utf-8")
    return path
